# Generated by Django 4.0.4 on 2022-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0014_templateresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
