# Generated by Django 4.0.4 on 2022-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0016_resume_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='clg_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='qulification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
